---
title: "ESM262_Assignment4"
author: "Alex Brown"
date: "5/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(magrittr)
```

###Test data

###Price Data
```{r}

### In Polyneisan Francs
price_data <- c("4000","15000", "20000", "25000", "20000") %>%
 as.tibble %>%
 mutate(fish = c("parrotfish", "unicornfish", "bonito", "yellowfin","swordfish")) %>%
  magrittr::set_colnames(value = c("price", "fish")) %>%
 mutate(price = parse_double(price, na = "0"))

```

###Fish Caught
```{r}

### create vector of possible fish

possible.fish = c("parrot fish","unicorn fish","bonito","yellowfin","swordfish")

### number of fish caught on northside

fish_north <- sample(possible.fish, size=20, replace=T) %>%
 as_tibble %>%
 group_by(value) %>%
 count() %>%

 magrittr::set_colnames(value = c("fish", "caught"))

### number of fish caught on eastside

fish_east <- sample(possible.fish, size=20, replace=T) %>%
 as_tibble %>%
 group_by(value) %>%
 count() %>%
 magrittr::set_colnames(value = c("fish", "caught"))

### number of fish caught on westside

fish_west <- sample(possible.fish, size=20, replace=T) %>%
 as_tibble %>%
 group_by(value) %>%
 count() %>%
 magrittr::set_colnames(value = c("fish", "caught"))

### combine all together

fish_all <- left_join(fish_north, fish_east, by= "fish")

catch_location_data <- left_join(fish_all, fish_west, by= "fish") %>%
 as.tibble()

as.numeric(catch_location_data$north)

#some runs have NAs instead of zeros from the sample of possible fish. This is in case that happens

catch_location_data[is.na(catch_location_data)] <- 0
```

####Run Function


```{r}

source("R/calc_fisheries_data.R")

summary <- fish_summary(catch_location_data = catch_location_data, price_data = price_data, graph = TRUE)

summary
```


```{r}

library(tidyverse)
library(dplyr)
```

### Create test data


```{r}

### create vector of possible fish


possible.fish = c("parrotfish","unicornfish","bonito","yellowfin","swordfish")

###Fish Catch Data


### number of fish caught on northside

catch_north <- sample(possible.fish, size=20, replace=T) %>%
 as_tibble %>%
 group_by(value) %>%
 count()

colnames(catch_north) <- c("fish", "north")
### number of fish caught on eastside


catch_east <- sample(possible.fish, size=20, replace=T) %>%
 as_tibble %>%
 group_by(value) %>%
 count()

colnames(catch_east) <- c("fish", "east")

### number of fish caught on westside

catch_west <- sample(possible.fish, size=20, replace=T) %>%
 as_tibble %>%
 group_by(value) %>%
 count()

colnames(catch_west) <- c("fish", "west")

### combine all together

catch_all_1 <- left_join(catch_north, catch_east, by= "fish")


catch_location_data <- left_join(catch_all_1, catch_west, by= "fish")

### Price Data

price_data <- c("4000","15000", "20000", "25000", "20000") %>%
 as_tibble()

colnames(price_data) <- c("price")

rownames(price_data) <- c("parrot", "unicorn", "bonito", "yellowfin","swordfish")

# because possible.fish was a factor catch1 will be a factor
summary(catch_location_data)


# if we want summary to be more useful - make this a factor

catch_north = as.factor(catch_location_data)

# to quickly get frequencies of different fish and to plot

summary(catch_location_data)

plot(catch_location_data$north, col="blue")
```
